version: '3.5'

services:
  frontend:
    build:
      context: ./src/frontend
      port: 
        - "3000:3000"
      depends_on:
        - backend
  
  backend:
    build:
      context: ./src/backend
      environment:
      ports:
        - "8000:8000"
