# Use an official Python runtime as a parent image
FROM python:3.11.7-alpine3.19

RUN apk add --update alpine-sdk

# Set the working directory to /app
RUN mkdir -p /app
WORKDIR /app

# Copy only the requirements files to the container
COPY ./pyproject.toml ./poetry.lock ./requirements.txt ./

# Set environment variables
# ENV PYTHONDONTWRITEBYTECODE 1
# ENV PYTHONUNBUFFERED 1

# # Install dependencies
RUN pip install --upgrade --progress-bar off pyarrow
# RUN pip install --progress-bar off -r requirements.txt
# RUN poetry config virtualenvs.create false
# RUN poetry install --no-interaction --no-ansi


# # Copy the application code to the container
# COPY ./ ./

# # uvicorn main:app --reload
# CMD ["uvicorn", "main:app", "--reload"]